#!/bin/sh
# postinst script for databank
#
# see: dh_installdeb(1)

set -e

# Source debconf library.
. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/postinst.mysql

paramfile=/etc/default/databank/db.sh
dbc_generate_include=sh:$paramfile
dbc_go databank $@

# Ask questions
db_get databank/email
dbemail="$RET"
#echo "Email id is:" $dbemail

db_get databank/smtpserver
dbsmtp="$RET"

db_get databank/store
dbstore="$RET"

db_get databank/uri
dburi="$RET"

db_get databank/password
dbpasswd="$RET"

#Modify the ini files
CONFIG_FILE1=/etc/default/databank/production.ini
CONFIG_FILE2=/etc/default/databank/development.ini
CONFIG_FILE3=/etc/default/databank/sss.conf.json
#replace email
TARGET_KEY=email_to
echo "Setting email Id: " $dbemail
#Sed syntax: sed s/a/b/ or sed s,a,b,
sed -i "s/\($TARGET_KEY *= *\).*/\1$dbemail/" $CONFIG_FILE1
sed -i "s/\($TARGET_KEY *= *\).*/\1$dbemail/" $CONFIG_FILE2
#replace smtp server
echo "Setting SMTP Server: " $dbsmtp
TARGET_KEY=smtp_server
sed -i "s,\($TARGET_KEY *= *\).*,\1$dbsmtp," $CONFIG_FILE1
sed -i "s,\($TARGET_KEY *= *\).*,\1$dbsmtp," $CONFIG_FILE2
#replace granary store
echo "Setting Data store: " $dbstore
TARGET_KEY=granary.store
sed -i "s,\($TARGET_KEY *= *\).*,\1$dbstore," $CONFIG_FILE1
sed -i "s,\($TARGET_KEY *= *\).*,\1$dbstore," $CONFIG_FILE2
#replace granary uri root
echo "Setting Base URI: " $dburi
TARGET_KEY=granary.uri_root
#[ $dburi != "*/" ] && dburi="$dburi""/"
dburi=${dburi%/}
dburi="$dburi""/"
sed -i "s,\($TARGET_KEY *= *\).*,\1$dburi," $CONFIG_FILE1
sed -i "s,\($TARGET_KEY *= *\).*,\1$dburi," $CONFIG_FILE2
TARGET_KEY1='    "base_url"'
TARGET_KEY2='    "db_base_url"'
val1='"'$dburi'swordv2/",'
val2='"'$dburi'",'
sed -i "s|\($TARGET_KEY1 *: *\).*|\1$val1|" $CONFIG_FILE3
sed -i "s|\($TARGET_KEY2 *: *\).*|\1$val2|" $CONFIG_FILE3
#replace the database connection string
TARGET_KEY=sqlalchemy.url
echo "Setting Database connection string: "
chmod 744 $paramfile
. $paramfile
dburl=mysql://$dbuser:$dbpass@localhost:3306/$dbname
sed -i "s^\($TARGET_KEY *= *\).*^\1$dburl^" $CONFIG_FILE1
sed -i "s^\($TARGET_KEY *= *\).*^\1$dburl^" $CONFIG_FILE2

echo "Setting configuration files"
#Link config files
ln -sf /etc/default/databank/production.ini /var/lib/databank/production.ini
ln -sf /etc/default/databank/development.ini /var/lib/databank/development.ini
ln -sf /etc/default/databank/sss.conf.json /var/lib/databank/sss.conf.json
ln -sf /etc/default/databank/databank_wsgi /etc/apache2/sites-available/databank_wsgi
ln -sf /etc/default/databank/databank_ve26_wsgi /etc/apache2/sites-available/databank_ve26_wsgi
ln -sf /etc/default/databank/databank_ve27_wsgi /etc/apache2/sites-available/databank_ve27_wsgi
echo "Creating directory for databank,cache and log"
#Create dirs and change ownership and permissions
# ownership and permissions for /var/lib/databank
chgrp -R www-data /var/lib/databank/
chmod -R 770 /var/lib/databank/
# ownership and permissions for /var/log/databank
mkdir -p /var/log/databank
chgrp -R www-data /var/log/databank/
chmod -R 770 /var/log/databank/
# ownership and permissions for /var/cache/databank
mkdir -p /var/cache/databank
chgrp -R www-data /var/cache/databank/
chmod -R 770 /var/cache/databank/
# ownership and permissions /etc/default/databank
chgrp -R www-data /etc/default/databank/
chmod -R 770 /var/cache/databank/
# ownership and permissions granary.store
mkdir -p $dbstore
cp /var/lib/databank/persisted_state.json $dbstore
chgrp -R www-data $dbstore
chmod -R 770 $dbstore

#Setup the python virtual environment
echo "Setting python environment"
virtualenv --no-site-packages /var/lib/databank/
cd /var/lib/databank/
. bin/activate
# Get the version of python being used
if [ -d /var/lib/databank/lib/python2.6/ ]
then
  py_site=databank_ve26_wsgi
else
  py_site=databank_ve27_wsgi
fi

easy_install -U distribute
pip install -r requirements.txt

#Setup the database and add the user password
echo "Configuring the database"
cd /var/lib/databank
paster setup-app production.ini
python add_user.py admin $dbpasswd $dbemail

#Configure SOLR and message workers in supervisor
echo "Configuring SOLR and Supervisor"
db_get databank/confsolr
dbconf="$RET"
installstatus=`dpkg-query -W -f='${Status}' solr-tomcat`
if [ "$installstatus" = "install ok installed" ]
then
    if [ "$dbconf" = "true" ]
    then
        if [ -f /etc/init.d/tomcat6 ]
        then
            invoke-rc.d tomcat6 stop
        fi
        if [ -f /etc/init.d/supervisor ]
        then
            invoke-rc.d supervisor stop
        fi
        cp /etc/solr/conf/schema.xml /etc/solr/conf/schema.xml.bak
        ln -sf /etc/default/databank/schema.xml /etc/solr/conf/schema.xml
        ln -sf /var/lib/databank/message_workers/workers_available/worker_broker.conf /etc/supervisor/conf.d/worker_broker.conf
        ln -sf /var/lib/databank/message_workers/workers_available/worker_solr.conf /etc/supervisor/conf.d/worker_solr.conf
        if [ -f /etc/init.d/tomcat6 ]
        then
            invoke-rc.d tomcat6 start
        fi
        if [ -f /etc/init.d/supervisor ]
        then
            invoke-rc.d supervisor start
        fi
    else
        echo "***********************************************************"
        echo "SOLR has not been configured for Databank."
        echo "The instructions for doing so are available at"
        echo "/usr/share/doc/databank/ConfiguringSOLR.txt"
        echo "***********************************************************"
    fi
else
    echo "***********************************************************"
    echo "SOLR has not been configured for Databank."
    echo "The instructions for doing so are available at"
    echo "/usr/share/doc/databank/ConfiguringSOLR.txt"
    echo "***********************************************************"
fi

#Enable site in apache
echo "Adding databank to Apache"
a2dissite default
a2dissite default-ssl
a2ensite $py_site

#Start Apache
invoke-rc.d apache2 reload
invoke-rc.d apache2 start

echo ===========================================================
echo Databank has been successfully installed
echo
echo Your Databank instance is available at http://localhost
echo Databank\'s home directory is /var/lib/databank
echo Data is stored under $dbstore
echo
echo To get started, visit the Databank homepage at http://localhost
echo
echo This paackage is brought to you by the Dataflow Team
echo http://dataflow.ox.ac.uk
echo ===========================================================

db_stop
